import './globals.css'
import { Toaster } from 'sonner'
import type { Metadata } from 'next'
import { Geist, Space_Mono } from 'next/font/google'
import { ThemeProvider } from '@/shared/components/theme-provider'

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist',
})
const spaceMono = Space_Mono({
  variable: '--font-space-mono',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: 'Shortly',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      <body className={`${geist.variable} ${spaceMono.variable} antialiased `}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
